"""empty message

Revision ID: 4276a4003a05
Revises: 684468014e70
Create Date: 2019-03-30 10:38:49.235203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4276a4003a05'
down_revision = '684468014e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'body_html')
    # ### end Alembic commands ###
